# Change these first
owner: CcNicebruh # Your GitHub organization or username, where this repository lives
repo: aqurusstatuspage # The name of this repository

sites:
  - name: Minecraft Survival Server
    check: "tcp-ping"
    url: play.aqurusmc.xyz
    port: 25565
  - name: Main Website
    url: https://aqurusmc.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aqurusmc.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AQur Us Craft
  introTitle: "อัพไทม์เซิฟ AQur Us"
  introMessage: นี่คีออัพไทม์ เอาไว้เช็คว่าอะไรออนไลน์เเล้วบ้าง หรีอยังไม่ออนไลน์
  navbar:
    - title: Status
      href: /
#     - title: GitHub
#       href: https://github.com/$OWNER/$REPO
    - title: Main Site
      href: https://aqurusmc.xyz
    - title: Discord
      href: https://discord.gg/kQ2R4hcK9v

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
